In [13]:
import pandas as pd

df = pd.read_csv("C:/Users/267206/Desktop/Data_Analyst_Projects/OLA_Data_Analytics_Project/ola_excel_data.csv", low_memory=False)

In [14]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,Personal & Car related issue,NaN,NaN,444.0,NaN,0.0,NaN,NaN,#NAME?,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158.0,Cash,13.0,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386.0,UPI,40.0,4.2,4.8,#NAME?,NaN
3,2024-07-22 3:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,NaN,NaN,384.0,NaN,0.0,NaN,NaN,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822.0,Credit Card,45.0,4.0,3.0,#NAME?,NaN

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        40539 non-null  str
 1   Time                        40539 non-null  str
 2   Booking_ID                  40539 non-null  str
 3   Booking_Status              40539 non-null  str
 4   Customer_ID                 40539 non-null  str
 5   Vehicle_Type                40539 non-null  str
 6   Pickup_Location             40539 non-null  str
 7   Drop_Location               40539 non-null  str
 8   V_TAT                       25207 non-null  float64
 9   C_TAT                       25207 non-null  float64
 10  Canceled_Rides_by_Customer  4079 non-null   str
 11  Canceled_Rides_by_Driver    7212 non-null   str
 12  Incomplete_Rides            25207 non-null  str
 13  Incomplete_Rides_Reason     1542 non-null   str
 14  Booking_Value               40539 non-null  float64
 15  Payment_Method              25207 non-null  str
 16  Ride_Distance               40539 non-null  float64
 17  Driver_Ratings              25207 non-null  float64
 18  Customer_Rating             25207 non-null  float64
 19  Vehicle Images              40539 non-null  str
 20  Unnamed: 20                 0 non-null      float64
dtypes: float64(7), str(14)
memory usage: 20.7 MB

In [16]:
df.describe(include='all')

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
count,40539,40539,40539,40539,40539,40539,40539,40539,25207.000000,25207.000000,...,7212,25207,1542,40539.000000,25207,40539.000000,25207.000000,25207.000000,40539,0.0
unique,26347,1440,40539,4,39657,7,50,50,NaN,NaN,...,4,2,3,NaN,4,NaN,NaN,NaN,1,NaN
top,2024-07-19 8:13:00,10:22:00,CNR7153255142,Success,CID954071,eBike,Indiranagar,Mysore Road,NaN,NaN,...,Personal & Car related issue,No,Customer Demand,NaN,Cash,NaN,NaN,NaN,#NAME?,NaN
freq,7,47,1,25207,3,5881,883,872,NaN,NaN,...,2500,23665,618,NaN,13708,NaN,NaN,NaN,40539,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170.845876,85.075574,...,NaN,NaN,NaN,547.193567,NaN,14.217297,3.997247,3.993474,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.474327,35.948584,...,NaN,NaN,NaN,534.800419,NaN,15.796990,0.576732,0.578972,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000000,25.000000,...,NaN,NaN,NaN,100.000000,NaN,0.000000,3.000000,3.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,55.000000,...,NaN,NaN,NaN,240.000000,NaN,0.000000,3.500000,3.500000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.000000,85.000000,...,NaN,NaN,NaN,385.000000,NaN,8.000000,4.000000,4.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.000000,115.000000,...,NaN,NaN,NaN,622.000000,NaN,26.000000,4.500000,4.500000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.000000,145.000000,...,NaN,NaN,NaN,2999.000000,NaN,49.000000,5.000000,5.000000,NaN,NaN

In [17]:
df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Vehicle Images', 'Unnamed: 20'],
      dtype='str')

In [18]:
# Step 1: Connect to MySQL
# Replace placeholders with your actual details

from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"                 # MySQL default user
password = quote_plus("Tanuj@2001")  # the password you set (encoded because of @)
host = "localhost"                # if running locally
port = "3306"                     # default MySQL port
database = "ola"   # the database you created in MySQL

engine = create_engine(
    f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into MySQL
table_name = "bookings"   # choose any table name

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'bookings' in database 'ola'.